### PR TITLE
Replace `request` and `request-promise` with `Axios`

### PR DESCRIPTION
**Pull request by Kyle-Ski**
Hello node-strava team 👋 I've taken a stab at replacing these deprecated packages, please take a look and test it out if you can. Thanks for all your work on this project!

**Replace Deprecated 'request' and 'request-promise' with Axios**

**Description:**
This pull request addresses the the deprecated `request` and `request-promise` libraries #155 . The change is aimed at modernizing the codebase, removing outdated dependencies, and ensuring better long-term maintenance of the project. The replacement to `axios` provides similar functionality while maintaining compatibility with newer versions of Node.js and reducing security risks related to deprecated packages.

**Key Changes:**

1. **Replaced 'request' and 'request-promise' with Axios**:
   - Updated the HTTP client throughout the codebase to use `axios` instead of `request` or `request-promise`.
   - Introduced a new Axios wrapper utility (`axiosUtility`) to encapsulate default configurations and provide a consistent error-handling mechanism across requests.

2. **Created Custom Error Classes**:
   - Added `StatusCodeError` and `RequestError` custom classes to replicate the error-handling behavior of `request-promise/errors`.
   - Updated all error-handling references to use the new custom error classes, ensuring backward compatibility.

3. **Refactored OAuth and Client Code**:
   - Updated `oauth.js` to use the new Axios wrapper for HTTP requests, including maintaining callback support and using Promises for better flexibility.
   - Refactored `client.js` to use `axiosInstance` to create a default request client similar to the old `request.defaults()` behavior.
   - Made minimal changes to maintain the existing structure and functionality while replacing the request mechanism.

4. **Preserved Original Behavior with Minimal Diff**:
   - Maintained the default request configuration (`strava.defaultRequest`) by replacing `request.defaults()` with `axiosInstance.create()`, ensuring default base URL and headers are consistently applied.
   - Kept the overall file structure as untouched as possible to reduce the size of the diff and make it easier to review.

5. **Testing Adjustments**:
   - Updated test setup to work with the new Axios implementation.
   - Ensured that all previous test cases, including error scenarios, were adapted to handle Axios' different error structures while maintaining backward compatibility.

**Backward Compatibility Considerations:**
- The custom error classes (`StatusCodeError`, `RequestError`) were implemented to ensure compatibility with existing error-handling patterns in the project.
- Callback support was retained alongside Promise-based usage to avoid breaking changes for consumers of the library.

**Testing and Verification:**
- All existing unit and integration tests have been executed and updated where necessary to reflect the Axios implementation.
- Manual testing has been performed to verify OAuth flows, API requests, and error-handling consistency please double check my work if you can 🙏.

**Rationale:**
The `request` and `request-promise` libraries have been deprecated, making them unsuitable for ongoing maintenance and potential security issues. By migrating to `axios`, this PR ensures the codebase stays up to date with modern standards and improves the developer experience with more comprehensive error handling and an actively maintained HTTP client.

Additionally, Axios was chosen over alternatives such as teeny-request because it offers a richer feature set out-of-the-box, such as built-in support for interceptors, automatic JSON transformations, and more robust error handling. Axios is also widely adopted and actively maintained, which makes it a reliable choice for long-term sustainability without adding unnecessary complexity to the codebase.

### CODE REVIEW

**Review by markstos — COMMENTED** [review]
I was going to ask why you choose Axios, but you anticipated the question and answered it. Thank you!

I need to take a second pass, but from the description this sounds like what we want.

Although, I would drop the callback the support and make a new major version. Other major projects like Mongoose have already dropped callback support. `await` / `async` has been available for several years now.

Are you interested to join as a co-maintainer? I continue to need to support this module in production so will also be around.

**Comment by Kyle-Ski** [comment]
Hey Mark, Happy Holidays! 🦃  I've refactored the affected code to rely on async/await and native Promises, as you suggested. I also removed `bluebird` as a dependency for the same reasons. Callback support has been removed from the updated files, though it remains in other parts of the repo as I didn't want to make this PR too big.

Regarding the co-maintainer role, I really appreciate the offer and have sent you an email sharing some thoughts and questions I have about taking on the role. I’d love to hear your perspective when you have a chance.

Let me know if there’s anything else you’d like addressed in this PR or if you need me to clarify anything further. Thanks again!

**Comment by markstos** [comment]
@Kyle-Ski I love that you also removed Bluebird dep. Same call I would have made. I'll reply to your email.

@wesleyschlenker Let's coordinate a time to get a new major release out.

**Comment by wesleyschlenker** [comment]
> @wesleyschlenker Let's coordinate a time to get a new major release out.
 Sounds good. Tomorrow should work for me. What are the breaking/potential breaking changes we're looking at here?

**Comment by markstos** [comment]
I created the conflict in yarn.lock here. It can be resolved by also upgrading the `cross-spawn` dep to 7.0.6 on this branch and this accepting this branch's version of `yarn.lock` as the resolution.

**Comment by Kyle-Ski** [comment]
I went ahead and updated the yarn.lock 👍

I also thought about the maintainer role, I'd love to accept and help out! Could be some fun things in the future for the project, and I'm in.

**Review by markstos — APPROVED** [review]

**Comment by mountainash** [comment]
Is there a reason for using Axios over the JavaScripts native `fetch()`? - which is also supported by Node, Bun and many other ECMAScript runtimes.

**Comment by markstos** [comment]
> Is there a reason for using Axios over the JavaScripts native fetch()? - which is also supported by Node, Bun and many other ECMAScript runtimes.

@mountainash As mentioned in the ticket, axios provides similar functionality to `request` / `request-promise`. Which different ECMAScript runtimes are you trying to run node-strava in?

According to Bun, it's a bug in Bun if Axios doesn't work there. They say:

> If a package works in Node.js but doesn't work in Bun, we consider it a bug in Bun. Please [open an issue](https://bun.sh/issues) and we'll fix it.

https://bun.sh/docs/runtime/nodejs-apis

**Comment by mountainash** [comment]
No no, it's not that it's not working... it works. But I was wondering why (the logic) the project choose to replace one dependency for another, when the language supports a fetch/promise method without the need for any dependency.

> PR ensures the codebase stays up to date with modern standards and improves the developer experience with more comprehensive error handling and an actively maintained HTTP client

Not taking away from the good work that was done, just that the statement above would have been more true to have used the native [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) and not rely on another dependency. Also likely faster, and smaller...

**Comment by markstos** [comment]
The  native Fetch API does not support retries, which is a feature we desire. See #156. Axios does.

But it's true there are lighterweight alternatives. 

In a fresh project, Axios adds 3.8M of dependencies to node_modules. In a real-world project, that could be a lot smaller, because other deps will likely share some of the same sub-dependencies.

But the fork `gaxios` adds only 1.3M of dependencies by the same test, largely with other popular modules as sub-dependencies.

So we could likely meet our needs by swapping `axios` for `gaxios`.

**Comment by mountainash** [comment]
Even 1.3 Mb seems massive for just boolean and a number count (to back off from) if you only need to do retries. With the advantage of not only saving size, but also not getting in the same situation of the project depreciating due to dependency on an unmaintained project.

**Comment by markstos** [comment]
> Even 1.3 Mb seems massive for just boolean and a number count (to back off from) if you only need to do retries.

As mentioned, we also need to support setting defaults.

Also, the 1.3Mb is the weight when added to an empty tree, not in practice. Check for yourself to see what the impact of replacing our old request-based modules with gaxios is.

If you have other ideas, work  on a PR and see if they are viable in practice.

**Pull request merged**
