### PR TITLE
Added group_events API endpoint

### PR DESCRIPTION
**Pull request by OzQu**

### CODE REVIEW

**Comment by OzQu** [comment]
These changes are just additions to the existing api wrapper. No changes to old features, so should be possible to promote in master.

**Comment by TimoSta** [comment]
Hi @OzQu, thanks for the contribution!

The code looks good to me, but could you please add a few test cases to cover the endpoints, as it is the case already for the majority of the library? Once this is done, I'll gladly merge it.

-- Timo

**Comment by OzQu** [comment]
Sure, I could. I'll add test shortly / in few days and then I'll update this PR.

**Comment by OzQu** [comment]
Took few days longer for me to find to do this... Anyway, now there are few tests. Didn't do any creating/deleting/joining/leaving from group events tests. I believe that would create notifications to others in same club.

**Comment by OzQu** [comment]
Also I noticed new endpoint for deleting group event. Added it also to the library.

**Comment by markstos** [comment]
Does this API endpoint still exist? I don't see any references to group_events here: https://developers.strava.com/docs/reference/

**Comment by markstos** [comment]
I don't see any reference on the Changelog to this being removed, but I don't see any documentation for it in the main documentation in the Swagger documentation. Looks like these API endpoints don't exist anymore, so I'm closing this.

**Pull request closed without merging**
