### PR TITLE
Feature/file exporting download

### PR DESCRIPTION
**Pull request by k-one-o-two**
This adds a feature to download GPX and TCX from a specified route

### CODE REVIEW

**Comment by markstos** [comment]
Could you update the documentation as well?

**Comment by k-one-o-two** [comment]
> 
> 
> Could you update the documentation as well?

done!

**Comment by markstos** [comment]
Thanks. I have some other pending changes I want to make. I'll do a final review-and-release of this and other changes as I have batch of time for this.

**Comment by k-one-o-two** [comment]
Hi! any news so far?

**Comment by markstos** [comment]
As I prepare for a major release, there's a new update landing tomorrow which will have a number of incompatibilities with this PR. The required changes will include:

 * ./lib/httpClient.js is used instead of ./lib/util.js
 * Callback API is not being supported for new features. Use only a promise-based API using `request-promise`. 
 * Testing against the live Strava API before was too painful and time-consuming. New tests should use `nock` to mock the Strava API.

You'll see examples in the new code of all of the above. While it sounds like a lot, I think the changes will be fast to make.

**Comment by markstos** [comment]
The master branch has now been updated if you want to try again. The changes are here: https://github.com/UnbounDev/node-strava-v3/releases

**Pull request closed without merging**
