### PR TITLE
added error handling for requestHelper

### PR DESCRIPTION
**Pull request by derekedelaney**
Added a check when the response returns an error as a 200.

Related to #56

### CODE REVIEW

**Comment by derekedelaney** [comment]
Not sure why the test are failing. 

_opinion :
`access_token` should not be required. It also seams like bad practice to make actual requests and manipulate real data in a test. Maybe mocking the endpoints and returning mocked JSON would be better._

**Comment by markstos** [comment]
If [my branch with Promise support was merged](https://github.com/UnbounDev/node-strava-v3/pull/58), it includes this kind of fix.  `lib/util.js` was replaced by `lib/httpClient.js`. You can search for `options.simple = true`. That's the logic that `request-promise` uses to express that non 2xx or 3xx responses should be treated as errors. Perhaps I should fork-in-release, since there's been no response for a year.

**Comment by derekedelaney** [comment]
I ended up forking this and including my changes. This repo has been abandoned for months/years. Promise support would be nice. Your changes look really good. I noticed some of these functions don’t work anymore since the api and website changes a few months ago. I think Strava is going through a bunch of development changes.

**Comment by arevenes** [comment]
@derekedelaney  Added almost the same fix for the same bug.. Looks like they are not looking into PRs though

**Comment by markstos** [comment]
Nope. It's time to fork-and-release to keep using this module. Strava is promoting a "code generation" approach,  where you would automatically generate the Node client code for their API.  Reference: https://github.com/strava/developers.strava.com/#client-code

Personally, I haven't found a code-gen client for an API that I loved using.

**Comment by markstos** [comment]
Closing in favor of the fix in my promise branch.

**Pull request closed without merging**
