### PR TITLE
Add support for explicit configuration. Fixes #50

### LINKED ISSUE #50: wish: explicit configuration
I'm interested in using this module in a large project that already has a centralized configuration system in place. Would there be willingness to accept a pull request that allows an explicit config to be loaded?

```javascript
    var strava = require('strava-v3');
    strava.fetchConfig(config)
    strava.athlete.get(...);
```

This would be implemented by exposing the existing authenticator/fetchConfig() method on the main object and updating it to accept an explicit config. If an explicit configuration was provided, it would be preferred over the other options.

The change would be backwards compatible. If an explicit configuration was *not* provided, the functionality would remain as before.

### PR DESCRIPTION
**Pull request by markstos**
New API is:

        strava.config({..});

API is backwards compatible.

I chose to have the explicit configuration override the other methods. It's
fine with me you want to reverse the logic to allow environment variables to
override the explicit config.

### CODE REVIEW

**Comment by markstos** [comment]
I have second thoughts about this approach now. While it supports explicit configuration, it only updates the global singleton, which is not where you want to store your access token when you are fielding a lot of requests for different Oauth users. 

It's also inconvenient to explicitly pass an `access_token` to every API call for every different OAuth user.

I think Strava has the right approach with their Go-based rest client. This also similar to have the `moves-api` client works. 

The Go syntax translation would be: 

       var client = strava.newClient("<an-access-token>")

Then would save the access token for re-use in a *private instance* of an API client, instead of a *shared  global instance*.  The access token could be stored as "this.access_token" on the private client object.

I think my original contribution of `strava.config()` is still useful in the bootstrapping phase, but I think being able to save an access_token to a private instance of the Strava client is also a useful configuration feature (and could likely also be backwards compatible)

**Comment by markstos** [comment]
I made a major refactor so that apps that make lots of calls on behalf of OAuth users don't have pass the `access_token` to every...single..API call.  Details are in the most recent commit message:

https://github.com/UnbounDev/node-strava-v3/pull/55/commits/573f0739ec0ddcb38bfd0b493464e1fa8879bfc2

I also updated the README and tests to reflect the change.   If you want to use the instance-specific access tokens, just a create a new `strava api client` like this:

```js
var stravaApi = require('strava-v3');

// ... get access_token from somewhere
strava = stravaApi.client(access_token);
```

This `client` object does *not* reference the global config variables or the environment, so there's no change of intending to use one acess_token but accidentally using another.

This design is based on how Strava`s own REST client written in Go works.

The change is backwards compatible (with the exception of reverting the undocumented questionable behavior implemented in #18), but it's perhaps worth considering if a new major version should move completely over to explicit configuration and per-instance configuration to simplify the design further.

**Comment by markstos** [comment]
The new `.client()` method also takes an optional second argument of a custom `request` object, which has a number of interesting uses:

  - The request object can be replaced by a mocked object, to avoid making network calls when testing. This part of Strava's automated testing solution in their Go REST client.
  - The request object can be used to provide a custom user agent string. A useful default is already provided. This solves #59 
 - The user can generally customize or replace the user agent.

**Comment by neonboxx** [comment]
Hi @markstos, are you still working on this one? Would be great to have fix #61 👍

**Comment by markstos** [comment]
I'm closing this because the ra-fixes branch this is present in will be promoted to master soon.

**Comment by markstos** [comment]
H

**Pull request closed without merging**
