### PR TITLE
Activity id is not required by get()

### PR DESCRIPTION
**Pull request by igniteflow**
If not given, get() returns all activities within the other query params

### CODE REVIEW

**Comment by saintnicster** [comment]
While I originally was wanting to see something like this, realized that the API already has "athlete.listActivities", and that supports Strava's pagination.

**Comment by markstos** [comment]
I think this should be closed. I think there was some confusion between these two endpoints:

  * get a single activity: `GET https://www.strava.com/api/v3/activities/:id` (:id is **required** here)
  * get a list of activities: `GET https://www.strava.com/api/v3/athlete/activities` (notice the inclusion of *athlete* here).

This project already supports both endpoints. Neither has a documented variation that works with or without an /:id

**Comment by markstos** [comment]
I see now the poor docs made this unclear. I submitted 09c0bb80c42dc90a341fcb6c92f63e318f79bc73 to a branch I'm working on to clarify this.

The branch also adds Promise support and supports Oauth use-cases without passing the access_tokens to every call. Check it out: https://github.com/UnbounDev/node-strava-v3/pull/55

**Comment by markstos** [comment]
I'm closing this, but plan to merge my referenced documentation patch which clarifies the docs.

**Pull request closed without merging**
